/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Posttest4;

import java.awt.Color;
import javax.swing.JOptionPane;

/**
 *
 * @author USER
 */
public class latihan1 extends javax.swing.JFrame {

    /**
     * Creates new form latihan1
     */
    public latihan1() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        Nama1 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        nt1 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        bb1 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jPanel3 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        AD1 = new javax.swing.JSlider();
        jLabel5 = new javax.swing.JLabel();
        Reguler1 = new javax.swing.JRadioButton();
        Express1 = new javax.swing.JRadioButton();
        persen1 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        th1 = new javax.swing.JTextField();
        ps1 = new javax.swing.JButton();
        ulangi1 = new javax.swing.JButton();
        keluar1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tampilan1 = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(255, 0, 255));

        jLabel1.setBackground(new java.awt.Color(153, 0, 0));
        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("     Form Pelanggan");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(126, 126, 126)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(23, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(102, 102, 255));

        jLabel2.setText("Nama");

        Nama1.setText("Nama");
        Nama1.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                Nama1CaretUpdate(evt);
            }
        });
        Nama1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Nama1ActionPerformed(evt);
            }
        });
        Nama1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                Nama1KeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                Nama1KeyReleased(evt);
            }
        });

        jLabel3.setText("No. Telepon");

        nt1.setText("No. Telepon");
        nt1.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                nt1CaretUpdate(evt);
            }
        });
        nt1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                nt1KeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                nt1KeyReleased(evt);
            }
        });

        jLabel6.setText("Berat Barang");

        bb1.setText("  0");
        bb1.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                bb1CaretUpdate(evt);
            }
        });
        bb1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                bb1KeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                bb1KeyReleased(evt);
            }
        });

        jLabel7.setText("Kg");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Nama1)
                    .addComponent(nt1, javax.swing.GroupLayout.DEFAULT_SIZE, 190, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel6)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(bb1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Nama1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(nt1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bb1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        jSeparator2.setOrientation(javax.swing.SwingConstants.VERTICAL);

        jPanel3.setBackground(new java.awt.Color(102, 102, 255));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setText("Atur Diskon");
        jPanel3.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 11, -1, -1));

        AD1.setMajorTickSpacing(10);
        AD1.setPaintTicks(true);
        AD1.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                AD1StateChanged(evt);
            }
        });
        jPanel3.add(AD1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 31, 160, -1));

        jLabel5.setText("Jenis Jasa");
        jPanel3.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 73, -1, -1));

        buttonGroup1.add(Reguler1);
        Reguler1.setText("Reguler");
        Reguler1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Reguler1ActionPerformed(evt);
            }
        });
        jPanel3.add(Reguler1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, -1, -1));

        buttonGroup1.add(Express1);
        Express1.setText("Express");
        jPanel3.add(Express1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 100, -1, -1));

        persen1.setText("50%");
        jPanel3.add(persen1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 38, 30, 20));

        jLabel9.setText("Total Harga");
        jPanel3.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, -1, -1));
        jPanel3.add(th1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 150, 128, -1));

        ps1.setText("Proses");
        ps1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                ps1MousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                ps1MouseReleased(evt);
            }
        });
        ps1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ps1ActionPerformed(evt);
            }
        });

        ulangi1.setText("Ulangi");
        ulangi1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ulangi1ActionPerformed(evt);
            }
        });

        keluar1.setText("Keluar");
        keluar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                keluar1ActionPerformed(evt);
            }
        });

        tampilan1.setEditable(false);
        tampilan1.setColumns(20);
        tampilan1.setRows(5);
        jScrollPane1.setViewportView(tampilan1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator1)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(ps1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ulangi1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(keluar1)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jSeparator2, javax.swing.GroupLayout.DEFAULT_SIZE, 178, Short.MAX_VALUE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ps1)
                    .addComponent(ulangi1)
                    .addComponent(keluar1))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Nama1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Nama1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Nama1ActionPerformed

    private void Reguler1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Reguler1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Reguler1ActionPerformed

    private void keluar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_keluar1ActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_keluar1ActionPerformed

    private void AD1StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_AD1StateChanged
        // TODO add your handling code here:
        persen1.setText(String.valueOf(AD1.getValue()+"%"));
        
    }//GEN-LAST:event_AD1StateChanged

    private void Nama1CaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_Nama1CaretUpdate
        // TODO add your handling code here:
        if(Nama1.getText().length()==0 || 
                nt1.getText().length()==0 || 
                bb1.getText().length()==0 || 
                bb1.getText().matches("[0]")){ 
            ps1.setEnabled(false);
       }
        else{
            ps1.setEnabled(true);
        }
    }//GEN-LAST:event_Nama1CaretUpdate

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        Nama1.setText("");
        nt1.setText("");
        bb1.setText("");
    }//GEN-LAST:event_formWindowOpened

    private void nt1CaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_nt1CaretUpdate
        // TODO add your handling code here:
        if(Nama1.getText().length()==0 || 
                nt1.getText().length()==0 || 
                bb1.getText().length()==0 || 
                bb1.getText().matches("[0]")){ 
            ps1.setEnabled(false);
       }
        else{
            ps1.setEnabled(true);
        }
    }//GEN-LAST:event_nt1CaretUpdate

    private void bb1CaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_bb1CaretUpdate
        // TODO add your handling code here:
        if(Nama1.getText().length()==0 || 
                nt1.getText().length()==0 || 
                bb1.getText().length()==0 || 
                bb1.getText().matches("[0]")){ 
            ps1.setEnabled(false);
       }
        else{
            ps1.setEnabled(true);
        }
    }//GEN-LAST:event_bb1CaretUpdate

    private void ps1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ps1ActionPerformed
        // TODO add your handling code here:
        String Nama, NT, jasa = null;
        float BB;
        double hasil = 0;
        int diskon;
        Nama = Nama1.getText();
        NT = nt1.getText();
    
        
        BB = Float.parseFloat(bb1.getText());
        diskon = AD1.getValue();
        if(Reguler1.isSelected()==true){
            jasa = "Reguler";
            hasil = (11500*BB)-((11500*BB*diskon)/100);
            
        }
        else if(Express1.isSelected()==true){
            jasa = "Express";
            hasil = ((11500*1.5)*BB)-((11500*1.5)*BB*diskon)/100;
        }
        if(buttonGroup1.getSelection()==null|| BB<=0){
            JOptionPane.showMessageDialog(null,"Berat harus diisi tidak boleh 0 dan pilih jasa","konfirmasi",JOptionPane.INFORMATION_MESSAGE);
        }
        else{
            tampilan1.setText("========== Data Pelanggan Laundry Muslimah ==========\n"+
                    "\n-----------------------------------------------\n"+
                    "Nama\t: "+Nama+
                    "\nNo. Telepon\t: "+NT+
                    "\nBerat Barang\t: "+BB+
                    "\nAtur Diskon\t: "+diskon+"%"+
                    "\nJenis Jasa\t: "+jasa+
                    "\nTotal Harga\t: "+hasil);
        }
    }//GEN-LAST:event_ps1ActionPerformed

    private void ulangi1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ulangi1ActionPerformed
        // TODO add your handling code here:
        Nama1.setText("");
        nt1.setText("");
        bb1.setText("");
        buttonGroup1.clearSelection();
        AD1.setValue(50);
        tampilan1.setText("");
    }//GEN-LAST:event_ulangi1ActionPerformed

    private void Nama1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Nama1KeyPressed
        // TODO add your handling code here:
        Nama1.setBackground(Color.green);
        Nama1.setForeground(Color.LIGHT_GRAY);
    }//GEN-LAST:event_Nama1KeyPressed

    private void nt1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_nt1KeyPressed
        // TODO add your handling code here:
        nt1.setBackground(Color.GRAY);
        nt1.setForeground(Color.red);
    }//GEN-LAST:event_nt1KeyPressed

    private void nt1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_nt1KeyReleased
        // TODO add your handling code here:
        nt1.setBackground(Color.ORANGE);
        nt1.setForeground(Color.BLUE);
    }//GEN-LAST:event_nt1KeyReleased

    private void Nama1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Nama1KeyReleased
        // TODO add your handling code here:
        Nama1.setBackground(Color.CYAN);
        Nama1.setForeground(Color.MAGENTA);
    }//GEN-LAST:event_Nama1KeyReleased

    private void bb1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_bb1KeyPressed
        // TODO add your handling code here:
        bb1.setBackground(Color.PINK);
        bb1.setForeground(Color.GREEN);
    }//GEN-LAST:event_bb1KeyPressed

    private void bb1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_bb1KeyReleased
        // TODO add your handling code here:
        bb1.setBackground(Color.BLUE);
        bb1.setForeground(Color.ORANGE);
    }//GEN-LAST:event_bb1KeyReleased

    private void ps1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ps1MousePressed
        // TODO add your handling code here:
        ps1.setBackground(Color.red);
        ps1.setForeground(Color.PINK);
    }//GEN-LAST:event_ps1MousePressed

    private void ps1MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ps1MouseReleased
        // TODO add your handling code here:
        ps1.setBackground(Color.blue);
        ps1.setForeground(Color.GRAY);
    }//GEN-LAST:event_ps1MouseReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(latihan1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(latihan1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(latihan1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(latihan1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new latihan1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JSlider AD1;
    private javax.swing.JRadioButton Express1;
    private javax.swing.JTextField Nama1;
    private javax.swing.JRadioButton Reguler1;
    private javax.swing.JTextField bb1;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JButton keluar1;
    private javax.swing.JTextField nt1;
    private javax.swing.JLabel persen1;
    private javax.swing.JButton ps1;
    private javax.swing.JTextArea tampilan1;
    private javax.swing.JTextField th1;
    private javax.swing.JButton ulangi1;
    // End of variables declaration//GEN-END:variables
}
